### ISSUE TITLE
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

### ISSUE THREAD

**Issue by MathiasSong** [liuyixin-louis/OpenChatPaper#10]
Hello,

I am sorry again for opening another issue. 
I am trying to run this app on WSL Ubuntu 20.04.4 LTS using python 3.9.5 virtual environment. 
I appreciate your help. Thank you.

-----------------------------------------------
Frontend

Traceback (most recent call last):
  File "/home/matt_song/projects/openchat/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "/home/matt_song/projects/openchat/frontend.py", line 98, in <module>
    response = requests.post(
  File "/home/matt_song/projects/openchat/venv/lib/python3.9/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/matt_song/projects/openchat/venv/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/matt_song/projects/openchat/venv/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/matt_song/projects/openchat/venv/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/matt_song/projects/openchat/venv/lib/python3.9/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

----------------------------------------------------------
Backend

UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 10010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0

**Comment by liuyixin-louis** [comment]
It seems that something is wrong with your CUDA environment setting. Please use the CPU instead.
